// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250922090603_UpdateOnControllersAndDbContext")]
    partial class UpdateOnControllersAndDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Emoji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Emojis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hund",
                            LevelId = 1,
                            Symbol = "🐶"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Katt",
                            LevelId = 1,
                            Symbol = "🐱"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mus",
                            LevelId = 1,
                            Symbol = "🐭"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kanin",
                            LevelId = 1,
                            Symbol = "🐰"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Räv",
                            LevelId = 1,
                            Symbol = "🦊"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Björn",
                            LevelId = 1,
                            Symbol = "🐻"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Panda",
                            LevelId = 1,
                            Symbol = "🐼"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Koala",
                            LevelId = 1,
                            Symbol = "🐨"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Lejon",
                            LevelId = 1,
                            Symbol = "🦁"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Ko",
                            LevelId = 1,
                            Symbol = "🐮"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Gris",
                            LevelId = 1,
                            Symbol = "🐷"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Groda",
                            LevelId = 1,
                            Symbol = "🐸"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Apa",
                            LevelId = 1,
                            Symbol = "🐵"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Enhörning",
                            LevelId = 1,
                            Symbol = "🦄"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Kyckling",
                            LevelId = 1,
                            Symbol = "🐔"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Äpple",
                            LevelId = 2,
                            Symbol = "🍎"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Pizza",
                            LevelId = 2,
                            Symbol = "🍕"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Hamburgare",
                            LevelId = 2,
                            Symbol = "🍔"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Glass",
                            LevelId = 2,
                            Symbol = "🍦"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Munk",
                            LevelId = 2,
                            Symbol = "🍩"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Vattenmelon",
                            LevelId = 2,
                            Symbol = "🍉"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Pommes",
                            LevelId = 2,
                            Symbol = "🍟"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Tårta",
                            LevelId = 2,
                            Symbol = "🍰"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Choklad",
                            LevelId = 2,
                            Symbol = "🍫"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Öl",
                            LevelId = 2,
                            Symbol = "🍺"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Te",
                            LevelId = 2,
                            Symbol = "🍵"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Popcorn",
                            LevelId = 2,
                            Symbol = "🍿"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Aubergine",
                            LevelId = 2,
                            Symbol = "🍆"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Jordgubb",
                            LevelId = 2,
                            Symbol = "🍓"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Persika",
                            LevelId = 2,
                            Symbol = "🍑"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Fotboll",
                            LevelId = 3,
                            Symbol = "⚽"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Basket",
                            LevelId = 3,
                            Symbol = "🏀"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Rugby",
                            LevelId = 3,
                            Symbol = "🏈"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Tennis",
                            LevelId = 3,
                            Symbol = "🎾"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Pingis",
                            LevelId = 3,
                            Symbol = "🏓"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Badminton",
                            LevelId = 3,
                            Symbol = "🏸"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Simning",
                            LevelId = 3,
                            Symbol = "🏊"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Cykling",
                            LevelId = 3,
                            Symbol = "🚴"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Klättring",
                            LevelId = 3,
                            Symbol = "🧗"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Surfing",
                            LevelId = 3,
                            Symbol = "🏄"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Snowboard",
                            LevelId = 3,
                            Symbol = "🏂"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Hockey",
                            LevelId = 3,
                            Symbol = "🏒"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Boxning",
                            LevelId = 3,
                            Symbol = "🥊"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Gymnastik",
                            LevelId = 3,
                            Symbol = "🤸"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Handboll",
                            LevelId = 3,
                            Symbol = "🤾"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Läkare",
                            LevelId = 4,
                            Symbol = "👨‍⚕️"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Lärare",
                            LevelId = 4,
                            Symbol = "👩‍🏫"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Kock",
                            LevelId = 4,
                            Symbol = "👨‍🍳"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Mekaniker",
                            LevelId = 4,
                            Symbol = "👩‍🔧"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Brandman",
                            LevelId = 4,
                            Symbol = "👨‍🚒"
                        },
                        new
                        {
                            Id = 51,
                            Description = "Pilot",
                            LevelId = 4,
                            Symbol = "👩‍✈️"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Domare",
                            LevelId = 4,
                            Symbol = "👨‍⚖️"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Konstnär",
                            LevelId = 4,
                            Symbol = "👩‍🎨"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Forskare",
                            LevelId = 4,
                            Symbol = "👨‍🔬"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Programmerare",
                            LevelId = 4,
                            Symbol = "👩‍💻"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Svetsare",
                            LevelId = 4,
                            Symbol = "👨‍🏭"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Astronaut",
                            LevelId = 4,
                            Symbol = "👩‍🚀"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Artist",
                            LevelId = 4,
                            Symbol = "👨‍🎤"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Bonde",
                            LevelId = 4,
                            Symbol = "👩‍🌾"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Polis",
                            LevelId = 4,
                            Symbol = "👮"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Bil",
                            LevelId = 5,
                            Symbol = "🚗"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Taxi",
                            LevelId = 5,
                            Symbol = "🚕"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Buss",
                            LevelId = 5,
                            Symbol = "🚌"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Spårvagn",
                            LevelId = 5,
                            Symbol = "🚎"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Polisbil",
                            LevelId = 5,
                            Symbol = "🚓"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Ambulans",
                            LevelId = 5,
                            Symbol = "🚑"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Brandbil",
                            LevelId = 5,
                            Symbol = "🚒"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Van",
                            LevelId = 5,
                            Symbol = "🚐"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Lastbil",
                            LevelId = 5,
                            Symbol = "🚚"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Cykel",
                            LevelId = 5,
                            Symbol = "🚲"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Sparkcykel",
                            LevelId = 5,
                            Symbol = "🛴"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Moped",
                            LevelId = 5,
                            Symbol = "🛵"
                        },
                        new
                        {
                            Id = 73,
                            Description = "Motorcykel",
                            LevelId = 5,
                            Symbol = "🏍️"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Lok",
                            LevelId = 5,
                            Symbol = "🚂"
                        },
                        new
                        {
                            Id = 75,
                            Description = "Flygplan",
                            LevelId = 5,
                            Symbol = "✈️"
                        },
                        new
                        {
                            Id = 76,
                            Description = "Sol",
                            LevelId = 6,
                            Symbol = "🌞"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Regn",
                            LevelId = 6,
                            Symbol = "🌧️"
                        },
                        new
                        {
                            Id = 78,
                            Description = "Oväder",
                            LevelId = 6,
                            Symbol = "⛈️"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Regnbåge",
                            LevelId = 6,
                            Symbol = "🌈"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Tornado",
                            LevelId = 6,
                            Symbol = "🌪️"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Solros",
                            LevelId = 6,
                            Symbol = "🌻"
                        },
                        new
                        {
                            Id = 82,
                            Description = "Träd",
                            LevelId = 6,
                            Symbol = "🌳"
                        },
                        new
                        {
                            Id = 83,
                            Description = "Gran",
                            LevelId = 6,
                            Symbol = "🌲"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Kaktus",
                            LevelId = 6,
                            Symbol = "🌵"
                        },
                        new
                        {
                            Id = 85,
                            Description = "Palm",
                            LevelId = 6,
                            Symbol = "🌴"
                        },
                        new
                        {
                            Id = 86,
                            Description = "Blomma",
                            LevelId = 6,
                            Symbol = "🌸"
                        },
                        new
                        {
                            Id = 87,
                            Description = "Måne",
                            LevelId = 6,
                            Symbol = "🌙"
                        },
                        new
                        {
                            Id = 88,
                            Description = "Löv",
                            LevelId = 6,
                            Symbol = "🍂"
                        },
                        new
                        {
                            Id = 89,
                            Description = "Fjäril",
                            LevelId = 6,
                            Symbol = "🦋"
                        },
                        new
                        {
                            Id = 90,
                            Description = "Snö",
                            LevelId = 6,
                            Symbol = "❄️"
                        },
                        new
                        {
                            Id = 91,
                            Description = "Arena",
                            LevelId = 7,
                            Symbol = "🏟️"
                        },
                        new
                        {
                            Id = 92,
                            Description = "Villa",
                            LevelId = 7,
                            Symbol = "🏡"
                        },
                        new
                        {
                            Id = 93,
                            Description = "Strand",
                            LevelId = 7,
                            Symbol = "🏖️"
                        },
                        new
                        {
                            Id = 94,
                            Description = "Ö",
                            LevelId = 7,
                            Symbol = "🏝️"
                        },
                        new
                        {
                            Id = 95,
                            Description = "Poststation",
                            LevelId = 7,
                            Symbol = "🏤"
                        },
                        new
                        {
                            Id = 96,
                            Description = "Sjukhus",
                            LevelId = 7,
                            Symbol = "🏥"
                        },
                        new
                        {
                            Id = 97,
                            Description = "Bank",
                            LevelId = 7,
                            Symbol = "🏦"
                        },
                        new
                        {
                            Id = 98,
                            Description = "Hotell",
                            LevelId = 7,
                            Symbol = "🏨"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Park",
                            LevelId = 7,
                            Symbol = "🏞️"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Butik",
                            LevelId = 7,
                            Symbol = "🏪"
                        },
                        new
                        {
                            Id = 101,
                            Description = "Skola",
                            LevelId = 7,
                            Symbol = "🏫"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Köpcenter",
                            LevelId = 7,
                            Symbol = "🏬"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Fabrik",
                            LevelId = 7,
                            Symbol = "🏭"
                        },
                        new
                        {
                            Id = 104,
                            Description = "Tempel",
                            LevelId = 7,
                            Symbol = "🏯"
                        },
                        new
                        {
                            Id = 105,
                            Description = "Slott",
                            LevelId = 7,
                            Symbol = "🏰"
                        },
                        new
                        {
                            Id = 106,
                            Description = "Hjärta",
                            LevelId = 8,
                            Symbol = "❤️"
                        },
                        new
                        {
                            Id = 107,
                            Description = "Brusten",
                            LevelId = 8,
                            Symbol = "💔"
                        },
                        new
                        {
                            Id = 108,
                            Description = "Stjärna",
                            LevelId = 8,
                            Symbol = "⭐"
                        },
                        new
                        {
                            Id = 109,
                            Description = "Glans",
                            LevelId = 8,
                            Symbol = "✨"
                        },
                        new
                        {
                            Id = 110,
                            Description = "Blixt",
                            LevelId = 8,
                            Symbol = "⚡"
                        },
                        new
                        {
                            Id = 111,
                            Description = "Eld",
                            LevelId = 8,
                            Symbol = "🔥"
                        },
                        new
                        {
                            Id = 112,
                            Description = "Droppe",
                            LevelId = 8,
                            Symbol = "💧"
                        },
                        new
                        {
                            Id = 113,
                            Description = "Utrop",
                            LevelId = 8,
                            Symbol = "❗"
                        },
                        new
                        {
                            Id = 114,
                            Description = "Fråga",
                            LevelId = 8,
                            Symbol = "❓"
                        },
                        new
                        {
                            Id = 115,
                            Description = "Klar",
                            LevelId = 8,
                            Symbol = "✅"
                        },
                        new
                        {
                            Id = 116,
                            Description = "Fel",
                            LevelId = 8,
                            Symbol = "❌"
                        },
                        new
                        {
                            Id = 117,
                            Description = "Plus",
                            LevelId = 8,
                            Symbol = "➕"
                        },
                        new
                        {
                            Id = 118,
                            Description = "Minus",
                            LevelId = 8,
                            Symbol = "➖"
                        },
                        new
                        {
                            Id = 119,
                            Description = "Division",
                            LevelId = 8,
                            Symbol = "➗"
                        },
                        new
                        {
                            Id = 120,
                            Description = "Triangel",
                            LevelId = 8,
                            Symbol = "🔺"
                        },
                        new
                        {
                            Id = 121,
                            Description = "Glad",
                            LevelId = 9,
                            Symbol = "🙂"
                        },
                        new
                        {
                            Id = 122,
                            Description = "Ledsen",
                            LevelId = 9,
                            Symbol = "😢"
                        },
                        new
                        {
                            Id = 123,
                            Description = "Arg",
                            LevelId = 9,
                            Symbol = "😠"
                        },
                        new
                        {
                            Id = 124,
                            Description = "Kär",
                            LevelId = 9,
                            Symbol = "😍"
                        },
                        new
                        {
                            Id = 125,
                            Description = "Förvånad",
                            LevelId = 9,
                            Symbol = "😮"
                        },
                        new
                        {
                            Id = 126,
                            Description = "Spänd",
                            LevelId = 9,
                            Symbol = "😬"
                        },
                        new
                        {
                            Id = 127,
                            Description = "Chockad",
                            LevelId = 9,
                            Symbol = "😲"
                        },
                        new
                        {
                            Id = 128,
                            Description = "Frustrerad",
                            LevelId = 9,
                            Symbol = "😤"
                        },
                        new
                        {
                            Id = 129,
                            Description = "Ilska",
                            LevelId = 9,
                            Symbol = "😡"
                        },
                        new
                        {
                            Id = 130,
                            Description = "Nöjd",
                            LevelId = 9,
                            Symbol = "😊"
                        },
                        new
                        {
                            Id = 131,
                            Description = "Entusiastisk",
                            LevelId = 9,
                            Symbol = "😃"
                        },
                        new
                        {
                            Id = 132,
                            Description = "Förvirrad",
                            LevelId = 9,
                            Symbol = "😕"
                        },
                        new
                        {
                            Id = 133,
                            Description = "Nervös",
                            LevelId = 9,
                            Symbol = "😅"
                        },
                        new
                        {
                            Id = 134,
                            Description = "Lugn",
                            LevelId = 9,
                            Symbol = "😌"
                        },
                        new
                        {
                            Id = 135,
                            Description = "Rädd",
                            LevelId = 9,
                            Symbol = "😱"
                        },
                        new
                        {
                            Id = 136,
                            Description = "Blinkar",
                            LevelId = 10,
                            Symbol = "😉"
                        },
                        new
                        {
                            Id = 137,
                            Description = "Flinar",
                            LevelId = 10,
                            Symbol = "😏"
                        },
                        new
                        {
                            Id = 138,
                            Description = "Oseriös",
                            LevelId = 10,
                            Symbol = "🙃"
                        },
                        new
                        {
                            Id = 139,
                            Description = "Tänker",
                            LevelId = 10,
                            Symbol = "🤔"
                        },
                        new
                        {
                            Id = 140,
                            Description = "Njuter",
                            LevelId = 10,
                            Symbol = "😋"
                        },
                        new
                        {
                            Id = 141,
                            Description = "Busig",
                            LevelId = 10,
                            Symbol = "😜"
                        },
                        new
                        {
                            Id = 142,
                            Description = "Fnissar",
                            LevelId = 10,
                            Symbol = "🤭"
                        },
                        new
                        {
                            Id = 143,
                            Description = "Skämtar",
                            LevelId = 10,
                            Symbol = "😛"
                        },
                        new
                        {
                            Id = 144,
                            Description = "Cool",
                            LevelId = 10,
                            Symbol = "😎"
                        },
                        new
                        {
                            Id = 145,
                            Description = "Skrattar",
                            LevelId = 10,
                            Symbol = "😂"
                        },
                        new
                        {
                            Id = 146,
                            Description = "Imponerad",
                            LevelId = 10,
                            Symbol = "🤩"
                        },
                        new
                        {
                            Id = 147,
                            Description = "Rörd",
                            LevelId = 10,
                            Symbol = "🥹"
                        },
                        new
                        {
                            Id = 148,
                            Description = "Dreglar",
                            LevelId = 10,
                            Symbol = "🤤"
                        },
                        new
                        {
                            Id = 149,
                            Description = "Smälter",
                            LevelId = 10,
                            Symbol = "🫠"
                        },
                        new
                        {
                            Id = 150,
                            Description = "Kräks",
                            LevelId = 10,
                            Symbol = "🤮"
                        });
                });

            modelBuilder.Entity("backend.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            Number = 3
                        },
                        new
                        {
                            Id = 4,
                            Number = 4
                        },
                        new
                        {
                            Id = 5,
                            Number = 5
                        },
                        new
                        {
                            Id = 6,
                            Number = 6
                        },
                        new
                        {
                            Id = 7,
                            Number = 7
                        },
                        new
                        {
                            Id = 8,
                            Number = 8
                        },
                        new
                        {
                            Id = 9,
                            Number = 9
                        },
                        new
                        {
                            Id = 10,
                            Number = 10
                        });
                });

            modelBuilder.Entity("backend.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("Rounds")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LevelId = 1,
                            Rounds = 12,
                            Time = 45,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvatarId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.Emoji", b =>
                {
                    b.HasOne("backend.Models.Level", "Level")
                        .WithMany("Emojis")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("backend.Models.Record", b =>
                {
                    b.HasOne("backend.Models.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Records")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Level", b =>
                {
                    b.Navigation("Emojis");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
